'use client';

import React from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight } from 'lucide-react';
import { motion } from 'framer-motion';

function CompanyInfo() {
  return (
    <section className="w-[calc(100vw-2rem)] lg:w-[calc(100vw-8rem)] mt-16 bg-gray-50 rounded-lg p-6 md:p-8 shadow-md">
      <div className="max-w-4xl mx-auto">
        <motion.h2 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-2xl font-bold text-gray-800 mb-6"
        >
          About Our Company
        </motion.h2>
        
        <div className="flex flex-col md:flex-row gap-8">
          <motion.div 
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="md:w-1/3"
          >
            <div className="relative w-full aspect-square rounded-lg overflow-hidden shadow-md image-hover">
              <Image
                src="/images/company.jpg"
                alt="Balaji Hi-Tech Garment facility"
                fill
                className="object-cover"
                sizes="(max-width: 768px) 100vw, 33vw"
              />
            </div>
          </motion.div>
          
          <motion.div 
            initial={{ opacity: 0, x: 20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="md:w-2/3"
          >
            <p className="text-gray-700 mb-4 leading-relaxed">
              Balaji Hi-Tech Garment is a leading manufacturer of reusable cloth diapers, period panty and reusable sanitary pads, offering sustainable solutions for daily hygiene. At Balaji Hi-Tech Garment, we focus on eco-friendly, technical textile products that combine comfort, durability, and environmental care.
            </p>
            <p className="text-gray-700 mb-4 leading-relaxed">
              Our reusable products help reduce the massive burden of non-biodegradable waste generated by single-use hygiene items, making a positive impact on the environment. With an in-house lab facility and strong emphasis on research and development, Balaji Hi-Tech Garment continuously innovates for better performance and sustainability.
            </p>
            <p className="text-gray-700 mb-6 leading-relaxed">
              Trusted by clients for innovation and consistency, Balaji Hi-Tech Garment stands at the forefront of sustainable garment manufacturing in India.
            </p>
            
            <Link 
              href="/about" 
              className="inline-flex items-center gap-2 bg-primary/10 hover:bg-primary/20 text-primary-foreground px-4 py-2 rounded-md transition-colors"
            >
              Learn more about us
              <ArrowRight size={16} />
            </Link>
          </motion.div>
        </div>
      </div>
    </section>
  );
}

export default CompanyInfo;